### ISSUE TITLE
Some docs improvements

### ISSUE THREAD

**Issue by slavkoja** [RocketMan/plugin-imap-user-auth#1]
Hi,

i found link to your plugin on kanboard's forum, i tried it with my own dovecot server and it works. But i was some difficulties to get it work, then i want to suggest some improvements in readme from my point of view (i am sorry, my English not good to suggest exact phrasing).

As first, please mention that php-imap is required. I know, that it seems to be obvious, but i miss this point and i didn't check its installation first.

Second, please mention that for logins without domain parts, the "Domain" filed have to be empty. I need to enable login's debug in dovecot, to see it and not all must know how to debug it.

Add exact examples about "Mailbox" field setting, because not all are familiar with PHP docs reading, eg:

+ setting for 993 with explicit TLS and valid certificate
+ setting for 143 port with STARTTLS logins and valid certificate
+ setting for unix's socket connection (i don't know, is it possible?)
+ mention flag for not valid certificate at end as common note only
+ use something as "imap.example.org" as server name, the "example.tld" domains are for this

I suggest this order for TLS, STARTTLS and not valid certificate with respect of [RFC 8314](https://tools.ietf.org/html/rfc8314.html).

And finally, please remove needing of curly brackets in "Mailbox" field, they adds useless complexity.

regards

**Comment by RocketMan** [comment]
Hello @slavkoja , happy to hear this is working for you.  Many thanks for the valuable feedback!

Could you please review the README on the docfix branch?  I have tried to incorporate your suggestions.  https://github.com/RocketMan/plugin-imap-user-auth/tree/docfix

Further comments are welcome...

**Comment by slavkoja** [comment]
I took look on the new README version and seems OK for me. I have only one note about localhost line.

Perhaps you misunderstand my note about unix sockets, the localhost in you example is only another hostname, then as example is IMO useless (because it duplicates the first one). Unix domain sockets are way to connect network application via regular file (thus limited to one machine) and use standard network communication (but skip all TCP/UDP things). I am using this for my roundcube, to avoid to expose 143 port at all, but allow unencrypted connection from the same machine (encryption is useless overhead when communication doesn't reach network).

Unix domain socket's address looks eg. "unix://path/to/file". But AFAIK it is not supported on windows and by my investigation it is not supported by imap_open() funtion too (at least not mentioned anywhere, but i am not PHP expert).

Then once again, the localhost line is IMO useless and the hostname of the local machine often points to localhost (127.0.0.1, ::1) anyway.

**Comment by RocketMan** [comment]
Thanks for the follow-up.  PHP imap_open delegates to the UW IMAP c-client library, which unfortunately does not support unix domain sockets.

localhost is nice for people who do not know the exact FQDN of their server.  For example, maybe the server that provides IMAP services for 'example.com' is something like 's32.webhostingserver.com'.  In this case, we just type localhost rather than s32...  However that said, one will always need to supply the /novalidate-cert option with localhost, since of course, localhost will never match the certificate CN.  I am thinking we keep the localhost option, but I will change it to include /novalidate-cert.

**Comment by RocketMan** [comment]
One more thing:  I have changed the setting 'Mailbox' to 'IMAP Server'.  I think it is less confusing, since we are specifying only the server portion of the IMAP mailbox.  Also, as per your earlier suggestion, the use of curly braces is now optional... it will now accept them if you put them in or add them internally if you do not.

If you have a better suggestion for the name of the setting 'IMAP Server', do let me know...

Thanks again for your feedback.

**Comment by slavkoja** [comment]
Sure, terrible to decide ;-) IMO leave unsecure setups to users responsibility and suggest only secure options, but you are free to ignore me in this.

From my point of view, finished. Thanks.

**Comment by RocketMan** [comment]
Yes, you are right.  Better not to suggest insecure setups.  I am going to take localhost out.  Thanks again!

**Comment by RocketMan** [comment]
Changes merged to master.  Released v1.0.1.  Closing.
