### ISSUE TITLE
Test for required php-imap

### ISSUE THREAD

**Issue by sokai** [RocketMan/plugin-imap-user-auth#5]
Hey @RocketMan – I like your plug-in and it's very useful! #thx

I will propose to have a (better) test for the required `php-imap` on the server.

_Background:_ Yesterday I struggled a lot to get the plug-in running. I always got the message in the server logs  `"PHP message: Kanboard: user $IMAP_USERNAME authentication failure"`. At the end I found out that I missed to install `php-imap` on the server.

I came across [/Auth/IMAPUserAuthProvider.php#L60 + L61](https://github.com/RocketMan/plugin-imap-user-auth/blob/0f4ccfa8a56e2df7c87d9b1cd73d360d8b2e9bf4/Auth/IMAPUserAuthProvider.php#L60), where I would appreciate a better test and a more detailed/better error message …

Thanks and best regards in advance
Kai

**Comment by RocketMan** [comment]
Hello Kai,

I am glad you are finding the plugin useful.

Thank you for your suggestion to improve the error reporting of installation and configuration issues.  I have committed an enhancement which will report if php-imap is not installed, or if the configuration settings have not been provided.

Thank you again, kind regards, James

**Comment by slavkoja** [comment]
Hi,

I will not open new issue, because it seems to be related to this solution.

Current implementation breaks abdroid's Kanboard app's login. I tried it with not configured plugin, and i got multiple times message about missing configuration. I had not enough patience to test, if it will login me latter.

I suggest to move "php-imap" test into configuration dialog, where can be warning showed and leave login function clean, without any message.
